# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z2.xdc

# Block Designs: bd/Windows_data_Test/Windows_data_Test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test || ORIG_REF_NAME==Windows_data_Test} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_axi_dma_0_0/Windows_data_Test_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_dma_0_0 || ORIG_REF_NAME==Windows_data_Test_axi_dma_0_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_axi_dma_1_0/Windows_data_Test_axi_dma_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_dma_1_0 || ORIG_REF_NAME==Windows_data_Test_axi_dma_1_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_xbar_0/Windows_data_Test_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_xbar_0 || ORIG_REF_NAME==Windows_data_Test_xbar_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_axi_interconnect_0_0/Windows_data_Test_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_interconnect_0_0 || ORIG_REF_NAME==Windows_data_Test_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_xbar_1/Windows_data_Test_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_xbar_1 || ORIG_REF_NAME==Windows_data_Test_xbar_1} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_axi_interconnect_1_0/Windows_data_Test_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_interconnect_1_0 || ORIG_REF_NAME==Windows_data_Test_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_proc_sys_reset_0_0/Windows_data_Test_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_proc_sys_reset_0_0 || ORIG_REF_NAME==Windows_data_Test_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_processing_system7_0_1/Windows_data_Test_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_processing_system7_0_1 || ORIG_REF_NAME==Windows_data_Test_processing_system7_0_1} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_xlconcat_0_0/Windows_data_Test_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_xlconcat_0_0 || ORIG_REF_NAME==Windows_data_Test_xlconcat_0_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_INACT_DATA_FIFO_0/Windows_data_Test_INACT_DATA_FIFO_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_INACT_DATA_FIFO_0 || ORIG_REF_NAME==Windows_data_Test_INACT_DATA_FIFO_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_ila_0_0/Windows_data_Test_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_ila_0_0 || ORIG_REF_NAME==Windows_data_Test_ila_0_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_INACT_DATA_FIFO_1/Windows_data_Test_INACT_DATA_FIFO_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_INACT_DATA_FIFO_1 || ORIG_REF_NAME==Windows_data_Test_INACT_DATA_FIFO_1} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_ila_0_3/Windows_data_Test_ila_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_ila_0_3 || ORIG_REF_NAME==Windows_data_Test_ila_0_3} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_Windows_Data_Convert_0_1/Windows_data_Test_Windows_Data_Convert_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_Windows_Data_Convert_0_1 || ORIG_REF_NAME==Windows_data_Test_Windows_Data_Convert_0_1} -quiet] -quiet

# IP: ip/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_us_0/Windows_data_Test_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_us_0 || ORIG_REF_NAME==Windows_data_Test_auto_us_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_us_1/Windows_data_Test_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_us_1 || ORIG_REF_NAME==Windows_data_Test_auto_us_1} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_ds_0/Windows_data_Test_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_ds_0 || ORIG_REF_NAME==Windows_data_Test_auto_ds_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_0/Windows_data_Test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_pc_0 || ORIG_REF_NAME==Windows_data_Test_auto_pc_0} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_4/Windows_data_Test_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_pc_4 || ORIG_REF_NAME==Windows_data_Test_auto_pc_4} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_1/Windows_data_Test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_pc_1 || ORIG_REF_NAME==Windows_data_Test_auto_pc_1} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_2/Windows_data_Test_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_pc_2 || ORIG_REF_NAME==Windows_data_Test_auto_pc_2} -quiet] -quiet

# IP: bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_3/Windows_data_Test_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_pc_3 || ORIG_REF_NAME==Windows_data_Test_auto_pc_3} -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_axi_dma_0_0/Windows_data_Test_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_dma_0_0 || ORIG_REF_NAME==Windows_data_Test_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_axi_dma_0_0/Windows_data_Test_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_dma_0_0 || ORIG_REF_NAME==Windows_data_Test_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_axi_dma_1_0/Windows_data_Test_axi_dma_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_dma_1_0 || ORIG_REF_NAME==Windows_data_Test_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_axi_dma_1_0/Windows_data_Test_axi_dma_1_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_axi_dma_1_0 || ORIG_REF_NAME==Windows_data_Test_axi_dma_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_proc_sys_reset_0_0/Windows_data_Test_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_proc_sys_reset_0_0 || ORIG_REF_NAME==Windows_data_Test_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_proc_sys_reset_0_0/Windows_data_Test_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_proc_sys_reset_0_0 || ORIG_REF_NAME==Windows_data_Test_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_processing_system7_0_1/Windows_data_Test_processing_system7_0_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_processing_system7_0_1 || ORIG_REF_NAME==Windows_data_Test_processing_system7_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_ila_0_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_ila_0_0 || ORIG_REF_NAME==Windows_data_Test_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_ila_0_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_ila_0_0 || ORIG_REF_NAME==Windows_data_Test_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_ila_0_0/Windows_data_Test_ila_0_0_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_ila_0_3/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_ila_0_3 || ORIG_REF_NAME==Windows_data_Test_ila_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_ila_0_3/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_ila_0_3 || ORIG_REF_NAME==Windows_data_Test_ila_0_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_ila_0_3/Windows_data_Test_ila_0_3_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_us_0/Windows_data_Test_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_us_0 || ORIG_REF_NAME==Windows_data_Test_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_us_0/Windows_data_Test_auto_us_0_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_us_1/Windows_data_Test_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_us_1 || ORIG_REF_NAME==Windows_data_Test_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_us_1/Windows_data_Test_auto_us_1_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_ds_0/Windows_data_Test_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Windows_data_Test_auto_ds_0 || ORIG_REF_NAME==Windows_data_Test_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_ds_0/Windows_data_Test_auto_ds_0_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_0/Windows_data_Test_auto_pc_0_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_4/Windows_data_Test_auto_pc_4_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_1/Windows_data_Test_auto_pc_1_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_2/Windows_data_Test_auto_pc_2_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/ip/Windows_data_Test_auto_pc_3/Windows_data_Test_auto_pc_3_ooc.xdc

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/bd/Windows_data_Test/Windows_data_Test_ooc.xdc
