


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package Windows_data_Test_axi4stream_vip_1_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_INTERFACE_MODE     = 2;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_SIGNAL_SET         = 8'b00010111;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_DATA_WIDTH         = 128;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_ID_WIDTH           = 1;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_DEST_WIDTH         = 1;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_USER_WIDTH         = 0;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_TREADY         = 1;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_TSTRB          = 1;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_TKEEP          = 0;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_TLAST          = 1;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_ACLKEN         = 0;
      parameter Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(Windows_data_Test_axi4stream_vip_1_0_VIP_SIGNAL_SET, 
                        Windows_data_Test_axi4stream_vip_1_0_VIP_DEST_WIDTH,
                        Windows_data_Test_axi4stream_vip_1_0_VIP_DATA_WIDTH,
                        Windows_data_Test_axi4stream_vip_1_0_VIP_ID_WIDTH,
                        Windows_data_Test_axi4stream_vip_1_0_VIP_USER_WIDTH, 
                        Windows_data_Test_axi4stream_vip_1_0_VIP_USER_BITS_PER_BYTE,
                        Windows_data_Test_axi4stream_vip_1_0_VIP_HAS_ARESETN) Windows_data_Test_axi4stream_vip_1_0_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      Windows_data_Test_axi4stream_vip_1_0_slv_t  Windows_data_Test_axi4stream_vip_1_0_slv;
//      initial begin : START_Windows_data_Test_axi4stream_vip_1_0_SLAVE
//        Windows_data_Test_axi4stream_vip_1_0_slv = new("Windows_data_Test_axi4stream_vip_1_0_slv", `Windows_data_Test_axi4stream_vip_1_0_PATH_TO_INTERFACE);
//        Windows_data_Test_axi4stream_vip_1_0_slv.start_slave();
//      end

endpackage : Windows_data_Test_axi4stream_vip_1_0_pkg
