


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package Windows_data_Test_axi4stream_vip_0_0_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_INTERFACE_MODE     = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_SIGNAL_SET         = 8'b01100011;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_DATA_WIDTH         = 8;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_ID_WIDTH           = 1;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_DEST_WIDTH         = 1;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_USER_WIDTH         = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_TREADY         = 1;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_TSTRB          = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_TKEEP          = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_TLAST          = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(Windows_data_Test_axi4stream_vip_0_0_VIP_SIGNAL_SET, 
                        Windows_data_Test_axi4stream_vip_0_0_VIP_DEST_WIDTH,
                        Windows_data_Test_axi4stream_vip_0_0_VIP_DATA_WIDTH,
                        Windows_data_Test_axi4stream_vip_0_0_VIP_ID_WIDTH,
                        Windows_data_Test_axi4stream_vip_0_0_VIP_USER_WIDTH, 
                        Windows_data_Test_axi4stream_vip_0_0_VIP_USER_BITS_PER_BYTE,
                        Windows_data_Test_axi4stream_vip_0_0_VIP_HAS_ARESETN) Windows_data_Test_axi4stream_vip_0_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      Windows_data_Test_axi4stream_vip_0_0_mst_t  Windows_data_Test_axi4stream_vip_0_0_mst;
//      initial begin : START_Windows_data_Test_axi4stream_vip_0_0_MASTER
//        Windows_data_Test_axi4stream_vip_0_0_mst = new("Windows_data_Test_axi4stream_vip_0_0_mst", `Windows_data_Test_axi4stream_vip_0_0_PATH_TO_INTERFACE);
//        Windows_data_Test_axi4stream_vip_0_0_mst.start_master();
//      end



endpackage : Windows_data_Test_axi4stream_vip_0_0_pkg
