# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sources_1/ip/axi_vip_0/axi_vip_0.xci
# IP: The module: 'axi_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/axi_vip_0/axi_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vip_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sources_1/ip/axi_vip_0/axi_vip_0.xci
# IP: The module: 'axi_vip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/axi_vip_0/axi_vip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_vip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
