@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Apr 13 15:36:11 +0800 2024
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim CNN_Accelerator_system_Test_behav -key {Behavioral:sim_1:Functional:CNN_Accelerator_system_Test} -tclbatch CNN_Accelerator_system_Test.tcl -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/window_tb/window_tb_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/cnn/CNN_Accelerator_tb_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/conv/conv_tb_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/window_tb/windows_data_axi_test_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.sim/sim_1/behav/CNN_System_tb/CNN_Accelerator_system_Test_behav.wcfg -log simulate.log"
call xsim  CNN_Accelerator_system_Test_behav -key {Behavioral:sim_1:Functional:CNN_Accelerator_system_Test} -tclbatch CNN_Accelerator_system_Test.tcl -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/window_tb/window_tb_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/cnn/CNN_Accelerator_tb_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/conv/conv_tb_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sim_1/imports/behav/window_tb/windows_data_axi_test_behav.wcfg -view E:/Accelerator/Accelerator_Test_Windows/Accelerator.sim/sim_1/behav/CNN_System_tb/CNN_Accelerator_system_Test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
