# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sources_1/ip/ila_conv/ila_conv.xci
# IP: The module: 'ila_conv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/ila_conv/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_conv'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/ila_conv/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_conv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/ila_conv/ila_conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_conv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/Accelerator/Accelerator_Test_Windows/Accelerator.srcs/sources_1/ip/ila_conv/ila_conv.xci
# IP: The module: 'ila_conv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/ila_conv/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_conv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/ila_conv/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_conv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/Accelerator/Accelerator_Test_Windows/Accelerator.gen/sources_1/ip/ila_conv/ila_conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_conv'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
